apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    name: dev
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: php-pod
  labels:
    env: testing
    region: IN
spec:
  containers:
  - name: myweb-con
    image: httpd
    volumeMounts:
      - name: web-vol1
        mountPath: /usr/local/apache2/htdocs/
  volumes:
  - name: web-vol1
    persistentVolumeClaim:
      claimName: php-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: my-service-php
  labels:
    app: myweb-service
spec:
  selector:
    env: testing
  type: NodePort
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
